// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQI_zcTWl8gnRM6oc5x6VCHbxnFMntBbE',
    appId: '1:165807735275:web:4c6be901bcc6994f3199ae',
    messagingSenderId: '165807735275',
    projectId: 'user-authentication-syst-98bd7',
    authDomain: 'user-authentication-syst-98bd7.firebaseapp.com',
    storageBucket: 'user-authentication-syst-98bd7.firebasestorage.app',
    measurementId: 'G-5BJRJKP7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BXXFKvmhQizs99-S72PlkMCBCr2CM78',
    appId: '1:165807735275:android:7e1d8e34ddbce2833199ae',
    messagingSenderId: '165807735275',
    projectId: 'user-authentication-syst-98bd7',
    storageBucket: 'user-authentication-syst-98bd7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQI_zcTWl8gnRM6oc5x6VCHbxnFMntBbE',
    appId: '1:165807735275:web:17c87b4829ced55c3199ae',
    messagingSenderId: '165807735275',
    projectId: 'user-authentication-syst-98bd7',
    authDomain: 'user-authentication-syst-98bd7.firebaseapp.com',
    storageBucket: 'user-authentication-syst-98bd7.firebasestorage.app',
    measurementId: 'G-LQKCZ6697H',
  );
}
